# Copyright (c) 2022 Andy Belle-Isle

manifest:
  self:
    path: firmware

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: etlcpp
      url-base: https://github.com/ETLCPP

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v3.2-branch
      import:
        path-prefix: os
    - name: etl
      remote: etlcpp
      revision: d63be881a44879a3e17aa263368d5571823afba1
      path: firmware/lib/etl
